class_9_10_homework/pokedex/config/routes.rb
Rails.application.routes.draw do
  get 'pokehome/pokeindex'
  get '/pokemon' => 'pokehome#pokemon'

  root 'pokehome#pokeindex'

end

class_9_10_homework/pokedex/app/controllers/pokehome_controller.rb
class PokehomeController < ApplicationController
  def pokeindex
    pokemon_list = HTTParty.get('http://pokeapi.co/api/v1/pokedex/1/')
    pokemon_response = pokemon_list.parsed_response
    @pokemon_object = pokemon_response["pokemon"]
  end
  def pokemon
   pokeparams = params[:format]
   pokeurl = HTTParty.get('http://pokeapi.co/' + pokeparams)
   poke_response = pokeurl.parsed_response
   @poke_name = poke_response["name"]
   @poke_abilities = poke_response["abilities"]
   @poke_types = poke_response["types"]

   #This gets the pokemon image
   if poke_response["sprites"][0] == nil
   else
   poke_sprite = poke_response["sprites"][0]["resource_uri"]
   poke_sprite_url = HTTParty.get('http://pokeapi.co/' + poke_sprite)
   poke_image_response = poke_sprite_url.parsed_response
   poke_image_uri = poke_image_response["image"]
   @poke_image = ('http://pokeapi.co/' + poke_image_uri)
 end

   #This goes to the next evolution
   @next_evolutions = poke_response["evolutions"][0]
   if @next_evolutions == nil
   else
   @next_evolutions_name = @next_evolutions["to"]
   @next_evolutions_uri = @next_evolutions["resource_uri"]   
 end



  end
end

class_9_10_homework/pokedex/app/helpers/pokehome_helper.rb
module PokehomeHelper
end

class_9_10_homework/pokedex/app/views/pokehome/pokeindex.html.erb
<h1>Check out all the pokemon!</h1>
<br>
<img src="http://i.imgur.com/Z0iQ1DF.jpg?1">
<br>
<% @pokemon_object.each do |p| %>
<li><%= link_to p["name"], pokemon_path(p["resource_uri"])%></li>
<% end %>

class_9_10_homework/pokedex/app/views/pokehome/pokemon.html.erb
<br>
Pokemon: <%= @poke_name %>
<br>
<% if @poke_image == nil %>
<h1>No Image Available</h1>
<% else %>
<img src="<%= @poke_image %>">
<% end %>
<br>
Abilities:
<br>
<% @poke_abilities.each do |name|%>
<%= name["name"] %><br>
<% end %>
<br>
Types:
<br>
<% @poke_types.each do |name|%>
<%= name["name"] %><br>
<% end %>
<br>
<% if @next_evolutions == nil %>
No more evolutions!
<% else %>
Next Evolution: <%= link_to @next_evolutions_name , pokemon_path(@next_evolutions_uri)%>
<% end %>
<br>
<br>
<a href ="/">Back to Pokedex</a>
<br>